 export const featureList = [
    {mainText:"Lorem ipsum", subText:'Accessories & Ears', rating:9},
    {mainText:"Lorem ipsum", subText:'Arms', rating:15},
    {mainText:"Lorem ipsum", subText:'Background', rating:2},
    {mainText:"Lorem ipsum", subText:'Eye', rating:32},
    {mainText:"Lorem ipsum", subText:'Glasses', rating:3},
    {mainText:"Lorem ipsum", subText:'Hair & Hats', rating:2},
    {mainText:"Lorem ipsum", subText:'Head', rating:92},
    {mainText:"Lorem ipsum", subText:'Legs & Clothes', rating:2},
    {mainText:"Lorem ipsum", subText:'Mouth', rating:46},
    {mainText:"Lorem ipsum", subText:'Accessories & Ears', rating:9},
    {mainText:"Lorem ipsum", subText:'Arms', rating:15},
    {mainText:"Lorem ipsum", subText:'Background', rating:2},
    {mainText:"Lorem ipsum", subText:'Eye', rating:32},
    {mainText:"Lorem ipsum", subText:'Glasses', rating:3},
    {mainText:"Lorem ipsum", subText:'Hair & Hats', rating:2},
    {mainText:"Lorem ipsum", subText:'Head', rating:92},
    {mainText:"Lorem ipsum", subText:'Legs & Clothes', rating:2},
    {mainText:"Lorem ipsum", subText:'Mouth', rating:46},
    {mainText:"Lorem ipsum", subText:'Accessories & Ears', rating:9},
    {mainText:"Lorem ipsum", subText:'Arms', rating:15},
    {mainText:"Lorem ipsum", subText:'Background', rating:2},
    {mainText:"Lorem ipsum", subText:'Eye', rating:32},
    {mainText:"Lorem ipsum", subText:'Glasses', rating:3},
    {mainText:"Lorem ipsum", subText:'Hair & Hats', rating:2},
    {mainText:"Lorem ipsum", subText:'Head', rating:92},
    {mainText:"Lorem ipsum", subText:'Legs & Clothes', rating:2},
    {mainText:"Lorem ipsum", subText:'Mouth', rating:46},
 ]